services:
  - type: web
    name: autolux-django
    runtime: python
    buildCommand: |
      pip install -r src/requirements.txt
      python src/manage.py collectstatic --noinput
    startCommand: |
      mkdir -p /data
      chmod 777 /data
      python src/manage.py migrate --noinput
      gunicorn automax.wsgi:application --chdir src
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: autolux-ntbk.onrender.com
      - key: EMAIL_HOST_USER
        value: anasanu8865@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: pepr slon uvjq ggbt
      - key: DATABASE_NAME
        value: /data/db.sqlite3
    disk:
      name: data-disk
      mountPath: /data
      sizeGB: 1
