services:
  - type: web
    name: autolux-django
    runtime: python
    buildCommand: |
      pip install -r src/requirements.txt
      python src/manage.py collectstatic --noinput
    startCommand: |
      python src/manage.py migrate --noinput
      gunicorn automax.wsgi:application --chdir src
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: autolux-ntbk.onrender.com
      - key: EMAIL_HOST_USER
        value: anasanu8865@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: pepr slon uvjq ggbt
      - key: DATABASE_URL
        value: postgresql://autolux_db_user:5aQmV31cqOhnaIT2YDbnBvy487tv6Fq3@dpg-d158746uk2gs73bun24g-a/autolux_db  # Replace this!
