# Generated by Django 5.1.6 on 2025-02-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_listing_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='milege',
            new_name='mileage',
        ),
    ]
