# Generated by Django 5.1.6 on 2025-03-01 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_likedlisting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedlisting',
            old_name='liked',
            new_name='listing',
        ),
    ]
